"""
Dashboard configuration and constants.
"""

# Expected columns for prediction (based on the predictor step)
EXPECTED_COLUMNS = [
    "Order",
    "PID",
    "MS SubClass",
    "Lot Frontage",
    "Lot Area",
    "Overall Qual",
    "Overall Cond",
    "Year Built",
    "Year Remod/Add",
    "Mas Vnr Area",
    "BsmtFin SF 1",
    "BsmtFin SF 2",
    "Bsmt Unf SF",
    "Total Bsmt SF",
    "1st Flr SF",
    "2nd Flr SF",
    "Low Qual Fin SF",
    "Gr Liv Area",
    "Bsmt Full Bath",
    "Bsmt Half Bath",
    "Full Bath",
    "Half Bath",
    "Bedroom AbvGr",
    "Kitchen AbvGr",
    "TotRms AbvGrd",
    "Fireplaces",
    "Garage Yr Blt",
    "Garage Cars",
    "Garage Area",
    "Wood Deck SF",
    "Open Porch SF",
    "Enclosed Porch",
    "3Ssn Porch",
    "Screen Porch",
    "Pool Area",
    "Misc Val",
    "Mo Sold",
    "Yr Sold",
]

# Feature categories for organized input in the prediction form
FEATURE_CATEGORIES = {
    "Identification": ["Order", "PID"],
    "Lot Information": ["MS SubClass", "Lot Frontage", "Lot Area"],
    "Quality & Condition": ["Overall Qual", "Overall Cond"],
    "Year Information": ["Year Built", "Year Remod/Add"],
    "Basement": [
        "BsmtFin SF 1",
        "BsmtFin SF 2",
        "Bsmt Unf SF",
        "Total Bsmt SF",
        "Bsmt Full Bath",
        "Bsmt Half Bath",
    ],
    "Living Area": [
        "1st Flr SF",
        "2nd Flr SF",
        "Low Qual Fin SF",
        "Gr Liv Area",
        "Mas Vnr Area",
    ],
    "Rooms & Baths": [
        "Full Bath",
        "Half Bath",
        "Bedroom AbvGr",
        "Kitchen AbvGr",
        "TotRms AbvGrd",
    ],
    "Garage": ["Garage Yr Blt", "Garage Cars", "Garage Area"],
    "Outdoor & Porch": [
        "Wood Deck SF",
        "Open Porch SF",
        "Enclosed Porch",
        "3Ssn Porch",
        "Screen Porch",
        "Pool Area",
    ],
    "Miscellaneous": ["Fireplaces", "Misc Val", "Mo Sold", "Yr Sold"],
}

# Sample default values (typical median values for Ames Housing dataset)
SAMPLE_VALUES = {
    "Order": 1,
    "PID": 526301100,
    "MS SubClass": 20,
    "Lot Frontage": 70.0,
    "Lot Area": 9500,
    "Overall Qual": 6,
    "Overall Cond": 5,
    "Year Built": 1970,
    "Year Remod/Add": 1990,
    "Mas Vnr Area": 0,
    "BsmtFin SF 1": 400,
    "BsmtFin SF 2": 0,
    "Bsmt Unf SF": 500,
    "Total Bsmt SF": 900,
    "1st Flr SF": 1100,
    "2nd Flr SF": 0,
    "Low Qual Fin SF": 0,
    "Gr Liv Area": 1500,
    "Bsmt Full Bath": 0,
    "Bsmt Half Bath": 0,
    "Full Bath": 2,
    "Half Bath": 0,
    "Bedroom AbvGr": 3,
    "Kitchen AbvGr": 1,
    "TotRms AbvGrd": 6,
    "Fireplaces": 1,
    "Garage Yr Blt": 1970,
    "Garage Cars": 2,
    "Garage Area": 480,
    "Wood Deck SF": 0,
    "Open Porch SF": 40,
    "Enclosed Porch": 0,
    "3Ssn Porch": 0,
    "Screen Porch": 0,
    "Pool Area": 0,
    "Misc Val": 0,
    "Mo Sold": 6,
    "Yr Sold": 2010,
}
